[package]
name = "tinyminiscript"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { version = "0.32.7", default-features = false }
arrayvec = { version = "0.7.6", optional = true }

[lib]
crate-type = ["lib"]

[features]
default = ["dep:arrayvec"]

alloc = []
debug = []
